config/routes.rb
Findyourteam::Application.routes.draw do
  devise_for :profiles
  resources :profiles
  resources :teams
  root to: "start_pages#index"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attr_accessible :email, :password, :remember_me, :nickname, :skype, :avatar, :vk, :steam,
                  :info

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>"  }, :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_uniqueness_of :nickname

  belongs_to :team
end

# == Schema Information
#
# Table name: profiles
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  nickname               :string(255)
#  vk                     :string(255)
#  twitter                :string(255)
#  fb                     :string(255)
#  skype                  :string(255)
#  steam                  :string(255)
#  team_id                :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :title, :description, :owner_id
  validates_uniqueness_of :title
  validates_presence_of :title

  has_many :profiles

  after_save :set_team_id_to_team_owner
  before_destroy :clear_team_id

  def set_team_id_to_team_owner
    owner=Profile.find(self.owner_id)
    self.profiles << owner
  end

  def clear_team_id
    owner=Profile.find(self.owner_id)
    self.profiles.delete(owner)
  end
end

# == Schema Information
#
# Table name: teams
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :integer
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_profile!, except: [:show, :index]
  inherit_resources

  def edit
    edit! {
      unless profile_owner?
        redirect_to profile_path(current_profile.id) and return
      end
    }
  end


  def profile_owner?
    current_profile.id == params[:id].to_i
  end
end

app/controllers/start_pages_controller.rb
class StartPagesController < ApplicationController
  def index
    if profile_signed_in?
      redirect_to teams_path
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  inherit_resources
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :profile
  end

  def resource
    @resource ||= Profile.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:profile]
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_owner?
    current_profile.id == params[:id].to_i
  end
end

app/helpers/start_pages_helper.rb
module StartPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Findyourteam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="content">
    <%= render 'shared/menu' %>
    <div class="body">
      <%= link_to_function "Назад", "history.back()", class: "button" %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/profiles/edit.html.erb
<%= simple_form_for @profile, :html => {:multipart => true } do |f| %>
  <%= f.input :nickname, label: "Ник", placeholder: "Ник" %>
  <%= f.input :skype, label: "Skype", placeholder: "Skype" %>
  <%= f.input :vk, label: "Страница ВКонтакте", placeholder: "Страница ВКонтакте" %>
  <%= f.input :steam, label: "Профиль Steam", placeholder: "Ник в Steam" %>
  <%= f.file_field :avatar %>
  <%= f.input :info, as: :text, label: "Информация о себе" %>
  <%= f.submit 'Сохранить изменения', class: 'button' %>
  <!-- TODO: лейблы вынести в отдельную колонку -->
<% end %>

app/views/profiles/settings.html.erb
<%= simple_form_for @profile, :html => {:multipart => true } do |f| %>
  <%= f.input :nickname %>
  <%= f.input :skype %>
  <%= f.file_field :avatar %>
  <%= f.submit 'Сохранить изменения' %>
<% end %>

app/views/profiles/show.html.erb
<div class="profile_wrapper">
  <div class="left_side">
    <div class="avatar">
      <%= image_tag @profile.avatar.url(:medium) %>
    </div>
    <div class="edit">
      <p><%= link_to "Настройки", edit_profile_path(current_profile.id), class: "button" if profile_owner? %></p>
      <p><%= link_to "Пригласить в команду", root_path, class: "button" %></p>
    </div>
  </div>
  <div class="right_side">
    <h1>Страница пользователя <%= @profile.nickname %> <% if profile_owner? %> (Это Вы) <% end %></h1>
    <ul
      <li>
        Skype: <%= @profile.skype %>
    </li>
    <li>
      vk: <%= @profile.vk %>
  </li>
  <li>
    Steam: <%= @profile.steam %>
</li>
<li>
  Информация: <%= @profile.info %>
</li>
    </ul>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="menu">
  <div class="left">
    <%= link_to "Команды", root_path %>
  </div>
  <div class="right">
    <% if profile_signed_in? %>
      Вы вошли как: <%= link_to current_profile.nickname, profile_path(current_profile.id) %>
    <%= link_to 'Выйти', destroy_profile_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Войти', new_profile_session_path %>
  <% end %>
  </div>
</div>

app/views/start_pages/index.html.erb
<div class="wrapper">
  <div class="left_side">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
  <div class="right-side">
    <%= render :template => 'devise/registrations/new' %>
  </div>
  <div class="clearfix"></div>
  <div class="bottom-info">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
</div>